//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPagamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCartoes
    {
        public int Id { get; set; }
        public string NumeroCartao { get; set; }
        public string Nome { get; set; }
        public double Limite { get; set; }
    }
}
