//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto02_EventosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Convidados = new HashSet<Convidado>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "A data é obrigatória")]
        [Display(Name = "Data do Evento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Data { get; set; }

        [Required(ErrorMessage = "A descrição é obrigatória")]
        [Display(Name = "Descrição")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Descrição deve ter entre 4 e 50 dígitos")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O nome do responsável é obrigatório")]
        [Display(Name = "Responsável")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Responsável deve ter entre 4 e 50 dígitos")]
        public string Responsavel { get; set; }

        [Required(ErrorMessage = "O valor é obrigatório")]
        [Display(Name = "Valor (Reais)")]
        [DataType(DataType.Currency)]
        public double Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Convidado> Convidados { get; set; }
    }
}
